---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: manualarchivingjobs.btrix.cloud
spec:
  scope: Namespaced
  group: btrix.cloud
  names:
    kind: ManualArchivingJob
    plural: manualarchivingjobs
    singular: manualarchivingjob
    shortNames:
      - mas

  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true

            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

      additionalPrinterColumns:
        - name: Expire At
          type: string
          jsonPath: .spec.expireTime
          description: Time Browser will Expire

        - name: Start Url
          type: string
          jsonPath: .spec.startUrl
          description: Starting Url
