{{ $backup := false }}
{{- range $storage := .Values.storages -}}
  {{- if $storage.is_db_backup -}}
    {{- $backup = print "storage-" $storage.name }}

  {{- end }}
{{- end}}

{{- if $backup -}}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: {{ $.Values.crawler_namespace }}
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 60
      template:
        spec:
          restartPolicy: Never
          initContainers:
            - name: dump
              image: {{ .Values.mongo_image }}
              imagePullPolicy: {{ .Values.mongo_pull_policy }}
              volumeMounts:
                - name: backups
                  mountPath: /backups

              command:
                - /bin/bash
                - -c
                - mongodump --uri=$MONGO_DB_URL --archive=/backups/backup.archive

              env:
                - name: MONGO_DB_URL
                  valueFrom:
                    secretKeyRef:
                      name: mongo-auth
                      key: MONGO_DB_URL

          containers:
            - name: upload
              image: {{ .Values.minio_mc_image }}
              imagePullPolicy: {{ .Values.minio_pull_policy }}
              volumeMounts:
                - name: backups
                  mountPath: /backups

              command:
                - /bin/bash
                - -c
                - |
                  [[ "$ENDPOINT_URL" =~ (https?://[^/]+/)([^/]+)/(.*)$ ]];
                  origin=${BASH_REMATCH[1]};
                  bucket=${BASH_REMATCH[2]};
                  path=${BASH_REMATCH[3]};
                  
                  echo "endpoint: $ENDPOINT_URL"
                  echo "origin: $origin"
                  echo "bucket: $bucket"
                  echo "path: ${path}db-backup/"
                  
                  mc alias set BACKUP $origin $ACCESS_KEY $SECRET_KEY || exit 1;
                  mc cp /backups/backup.archive BACKUP/${bucket}/${path}db-backup/mongodb-$(date +%Y-%m-%d).archive || exit 2;
              env:
                - name: ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $backup }}
                      key: STORE_ACCESS_KEY

                - name: SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ $backup }}
                      key: STORE_SECRET_KEY

                - name: ENDPOINT_URL
                  valueFrom:
                    secretKeyRef:
                      name: {{ $backup }}
                      key: STORE_ENDPOINT_URL

          volumes:
            - name: backups
              emptyDir: {}

   {{- end }}