
{{- range untilStep 0 (int .Values.max_crawl_scale) 1 }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: crawl-instance-{{ . }}
value: -{{ . }}
globalDefault: false
description: "Priority for crawl instance #{{ . }}"

{{- end }}

# Lower Priority for Background Jobs
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: bg-jobs
value: -100
globalDefault: false
description: "Priority for background jobs"


