apiVersion: btrix.cloud/v1
kind: Job
metadata:
  name: "{{ id }}"
  labels:
    role: "background-job"
    btrix.org: {{ oid }}

spec:
  ttlSecondsAfterFinished: 300
  id: "{{ id }}"
  oid: "{{ oid }}"
  primary_file_path: "{{ primary_file_path }}"
  primary_storage_name: "{{ primary_storage_name }}"
  replica_file_path: "{{ replica_file_path }}"
  replica_storage_name: "{{ replica_storage_name }}"

  template:
    spec:
      backoffLimit: 5
      restartPolicy: Never
      podFailurePolicy:
        rules:
        - action: FailJob
          onExitCodes:
            containerName: rclone
            operator: NotIn
            values: [0]
      containers:
      - name: rclone
        image: rclone:latest
        env:
        - name: RCLONE_CONFIG_PRIMARY_TYPE
          value: "s3"
        - name: RCLONE_CONFIG_PRIMARY_ACCESS_KEY_ID
          valueFrom:
            storages:
              name: "{{ primary_storage_name }}"
              key: access_key
        - name: RLCONE_CONFIG_PRIMARY_SECRET_ACCESS_KEY
          valueFrom:
            storages:
              name: "{{ primary_storage_name }}"
              key: secret_key
        - name: RCLONE_CONFIG_REPLICA_TYPE
          value: "s3"
        - name: RCLONE_CONFIG_REPLICA_ACCESS_KEY_ID
          valueFrom:
            storages:
              name: "{{ replica_storage_name }}"
              key: access_key
        - name: RCLONE_CONFIG_REPLICA_SECRET_ACCESS_KEY
          valueFrom:
              storages:
                name: "{{ replica_storage_name }}"
                key: secret_key
        command: ["rclone", "copyto", "--checksum", "{{ primary_file_path }}", "{{ replica_file_path }}"]
      
